### ISSUE TITLE
Path to package.json wrong after writing to lib/*

### ISSUE THREAD

**Issue by Draigs** [smartlook/smartlook-react-native-bridge#32]
After everything was written to lib/*, e.g. lib/commonjs/, the relative path to package.json doesn't work anymore. This leads to error executing tests in my project. A fix would be to replace the relative path
```
const SMARTLOOK_VERSION = require('../package.json').version;
```
with
```
const SMARTLOOK_VERSION = require('smartlook-react-native-wrapper/package.json').version;
```

Would love to fix it by creating a pull request, but looks like I'm not allowed to push and create a pull request. :/

**Comment by axeffwettercom** [comment]
Having the exact same problem.

**Comment by krystofcelba** [comment]
Hey, sorry for waiting. We are going to release a new version after the weekend with the fix. I will inform you about that.
