### ISSUE TITLE
Wireframe rendering mode doesn't work on Android

### ISSUE THREAD

**Issue by PrimulaX** [smartlook/smartlook-react-native-bridge#49]
I have this code in componentDidMount method: 
```
Smartlook.setup({ smartlookAPIKey: 'MY_API_KEY', startNewSession: true, fps: 2 });
Smartlook.setRenderingMode(Smartlook.RenderingMode.Wireframe);
Smartlook.startRecording();
 ```
 
 It's working on iOS but on Android It not even shows recordings in dashboard.

**Comment by krystofcelba** [comment]
Hi @PrimulaX,
sorry for the late response. I would like to ask if you still suffer from the issue? And if so, could you please tell me any details which could help me with isolating what is wrong? For example any logs from the running app. 

Thanks!

**Comment by PrimulaX** [comment]
Hi, I did switch to native rendering mode. I was unable to resolve the problem.

**Comment by SenNeonoveNoci** [comment]
@PrimulaX Without any detailed info, we cannot resolve the wireframe rendering mode issue.
